### ISSUE TITLE
Separate Vector[23] into Int and Float classes

### ISSUE THREAD

**Issue by SOF3** [pmmp/Math#3]

**Comment by dktapps** [comment]
Is it just me who sees "an hour from now" on this issue?

**Comment by dktapps** [comment]
For posterity: I stalled on this for a long time because there's some functionality in `Vector3` specifically that can't be easily adapted to an `IntVector3`. Anything that involves division or roots could result in a `FloatVector3` result.

A list of these that I picked up on so far:
- `getIntermediateWithXValue()`
- `getIntermediateWithYValue()`
- `getIntermediateWithZValue()`
- `normalize()`
- `divide()`
- `multiply()` (because it accepts a float input)

It's possible we could implement just a barebones `IntVector3` that only has the absolute bare minimum + a `toFloatVector3()` to allow conversion.

It also raises the question of how to avoid a whole bunch of duplicated code between the two classes.

**Comment by SOF3** [comment]
It is worth noting that, when we first discussed this 6 years ago, phpstan generics didn't exist/weren't as good. The main problem now is that we cannot stop people calling these float-specific methods if they share the same class.

**Comment by dktapps** [comment]
PHPStan generics don't work very well for this purpose sadly. Calling float methods on an int vector isn't a big deal though since Vector3 is de facto readonly since PM4 and will be language-level readonly in PM6.

**Comment by dktapps** [comment]
Decided not to go forward with this as it makes more sense to make a specialized structure within PM itself.
